
import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../componenets/Header'
import RestaurantCard from '../componenets/RestaurantCard'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>OpenTable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
       {/* CARDS */}
        <div className="py-3 px-36 mt-10 flex flex-wrap justify-center">
          <RestaurantCard />
        </div>
      </main>
    </>
  )
}
